all:
	g++ \
	otelcurl.cpp \
	-DOPENTELEMETRY_ABI_VERSION_NO=2 \
	-g \
	-Wall \
	-lopentelemetry_exporter_otlp_grpc \
	-lopentelemetry_exporter_ostream_span \
	-lopentelemetry_trace \
	-lopentelemetry_resources \
	-lcurl \
	-lcurlpp \
	-o otelcurl
